package com.edival.recioblog.core

object Constants {
    const val IMAGES_MT = "image/jpeg"
    const val PATH_IMAGES = "images"
    const val COLL_USERS = "Users"
    const val COLL_POSTS = "Posts"
    const val R_LOGIN = "login"
    const val R_SIGNUP = "signup"
    const val R_PROFILE = "profile"
    const val R_PROFILE_EDIT = "profile/edit"
    const val R_POST = "posts"
    const val R_MY_POSTS = "my_posts"
    const val R_NEW_POSTS = "posts/new"
    const val R_EDIT_POSTS = "posts/edit"
    const val R_DETAIL_POSTS = "posts/detail"
    const val USER_ARG = "user"
    const val POST_ARG = "post"
    const val F_ID_USER = "idUser"
    const val F_USERNAME = "username"
    const val F_IMG_URL = "imgUrl"
    const val F_NAME = "name"
    const val F_DESC = "description"
    const val F_CTG = "category"
    const val F_LIKES = "likes"
    const val PREFIX_IMG = "selected_image_"
    const val SUFFIX_IMG = ".jpg"
    const val FILE_PROVIDER = ".fileprovider"
}